name: Docker Build Backend

on:
  push:
    branches: [ dev-backend ]
  pull_request:
    branches: [ dev-backend ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      working-directory: ./esim-cloud-backend
      run: docker build . --file Dockerfile --tag esimcloud-django:$(date +%s)
