name: Lint

on:
    push:
      paths: [ 'eda-frontend/**', 'ArduinoFrontend/**' ]
    pull_request:
      paths: [ 'eda-frontend/**', 'ArduinoFrontend/**' ]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: hallee/eslint-action@master
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
