name: React Build and Tests

on:
  push:
    paths: [ 'eda-frontend/**' ]
  pull_request:
    paths: [ 'eda-frontend/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node js
      uses: actions/setup-node@v1
      with:
        node-version: 10.5.0
    - name: ESLint Check
      uses: hallee/eslint-action@1.0.1
    - name: Install packages,lint,build and Unit testing
      working-directory: ./eda-frontend
      run: |
        npm install
        CI=true npm run build
        CI=true npm test
